# Generated by Django 2.0.8 on 2018-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='signature_file',
            field=models.FileField(upload_to='signatures/'),
        ),
    ]
