# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('address', models.TextField(max_length=2000)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('political_municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='municipalities.Municipality')),
            ],
        ),
    ]
