# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
