# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_auto_20160403_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='bfs_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='language',
            field=models.CharField(default='de', max_length=10),
        ),
        migrations.AddField(
            model_name='municipality',
            name='main_municipality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
