# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0003_auto_20160428_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='canton',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
