# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0005_municipality_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
