# Generated by Django 2.0.3 on 2018-03-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0007_auto_20160624_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='political_municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='municipalities.Municipality'),
        ),
    ]
