# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0002_auto_20160403_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.IntegerField(null=True)),
                ('to_number', models.IntegerField(null=True)),
                ('sent_on', models.DateTimeField(null=True)),
                ('received_on', models.DateTimeField(null=True)),
                ('state', models.TextField(default='new')),
                ('alert', models.BooleanField(default=False)),
                ('number_of_signatures', models.IntegerField(default=0)),
                ('valid_signatures', models.IntegerField(null=True)),
                ('invalid_signatures', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipalities.Municipality')),
            ],
        ),
    ]
