# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='pdf_file',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
