# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
