# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_auto_20160508_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='called_on',
            field=models.DateTimeField(null=True),
        ),
    ]
