# Generated by Django 2.0.3 on 2018-03-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_mailing_called_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipalities.Municipality'),
        ),
    ]
